# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import circuitbreaker_pb2 as circuitbreaker__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in circuitbreaker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/circuitbreaker.Service/GetInfo',
                request_serializer=circuitbreaker__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=circuitbreaker__pb2.GetInfoResponse.FromString,
                _registered_method=True)
        self.UpdateLimits = channel.unary_unary(
                '/circuitbreaker.Service/UpdateLimits',
                request_serializer=circuitbreaker__pb2.UpdateLimitsRequest.SerializeToString,
                response_deserializer=circuitbreaker__pb2.UpdateLimitsResponse.FromString,
                _registered_method=True)
        self.ClearLimits = channel.unary_unary(
                '/circuitbreaker.Service/ClearLimits',
                request_serializer=circuitbreaker__pb2.ClearLimitsRequest.SerializeToString,
                response_deserializer=circuitbreaker__pb2.ClearLimitsResponse.FromString,
                _registered_method=True)
        self.UpdateDefaultLimit = channel.unary_unary(
                '/circuitbreaker.Service/UpdateDefaultLimit',
                request_serializer=circuitbreaker__pb2.UpdateDefaultLimitRequest.SerializeToString,
                response_deserializer=circuitbreaker__pb2.UpdateDefaultLimitResponse.FromString,
                _registered_method=True)
        self.ListLimits = channel.unary_unary(
                '/circuitbreaker.Service/ListLimits',
                request_serializer=circuitbreaker__pb2.ListLimitsRequest.SerializeToString,
                response_deserializer=circuitbreaker__pb2.ListLimitsResponse.FromString,
                _registered_method=True)
        self.ListForwardingHistory = channel.unary_unary(
                '/circuitbreaker.Service/ListForwardingHistory',
                request_serializer=circuitbreaker__pb2.ListForwardingHistoryRequest.SerializeToString,
                response_deserializer=circuitbreaker__pb2.ListForwardingHistoryResponse.FromString,
                _registered_method=True)


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLimits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearLimits(self, request, context):
        """Clear specific limits and use default.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDefaultLimit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLimits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListForwardingHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=circuitbreaker__pb2.GetInfoRequest.FromString,
                    response_serializer=circuitbreaker__pb2.GetInfoResponse.SerializeToString,
            ),
            'UpdateLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLimits,
                    request_deserializer=circuitbreaker__pb2.UpdateLimitsRequest.FromString,
                    response_serializer=circuitbreaker__pb2.UpdateLimitsResponse.SerializeToString,
            ),
            'ClearLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearLimits,
                    request_deserializer=circuitbreaker__pb2.ClearLimitsRequest.FromString,
                    response_serializer=circuitbreaker__pb2.ClearLimitsResponse.SerializeToString,
            ),
            'UpdateDefaultLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDefaultLimit,
                    request_deserializer=circuitbreaker__pb2.UpdateDefaultLimitRequest.FromString,
                    response_serializer=circuitbreaker__pb2.UpdateDefaultLimitResponse.SerializeToString,
            ),
            'ListLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLimits,
                    request_deserializer=circuitbreaker__pb2.ListLimitsRequest.FromString,
                    response_serializer=circuitbreaker__pb2.ListLimitsResponse.SerializeToString,
            ),
            'ListForwardingHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListForwardingHistory,
                    request_deserializer=circuitbreaker__pb2.ListForwardingHistoryRequest.FromString,
                    response_serializer=circuitbreaker__pb2.ListForwardingHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'circuitbreaker.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circuitbreaker.Service/GetInfo',
            circuitbreaker__pb2.GetInfoRequest.SerializeToString,
            circuitbreaker__pb2.GetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circuitbreaker.Service/UpdateLimits',
            circuitbreaker__pb2.UpdateLimitsRequest.SerializeToString,
            circuitbreaker__pb2.UpdateLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circuitbreaker.Service/ClearLimits',
            circuitbreaker__pb2.ClearLimitsRequest.SerializeToString,
            circuitbreaker__pb2.ClearLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDefaultLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circuitbreaker.Service/UpdateDefaultLimit',
            circuitbreaker__pb2.UpdateDefaultLimitRequest.SerializeToString,
            circuitbreaker__pb2.UpdateDefaultLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circuitbreaker.Service/ListLimits',
            circuitbreaker__pb2.ListLimitsRequest.SerializeToString,
            circuitbreaker__pb2.ListLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListForwardingHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/circuitbreaker.Service/ListForwardingHistory',
            circuitbreaker__pb2.ListForwardingHistoryRequest.SerializeToString,
            circuitbreaker__pb2.ListForwardingHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
